# Light e dark usam a mesma paleta de propósito.

[theme]
primaryColor = "#f0600c"
backgroundColor = "#fcfce4"
secondaryBackgroundColor = "#f0cc90"
textColor = "#070606"

[theme.sidebar]
backgroundColor = "#070606"
textColor = "#fcfce4"
primaryColor = "#f0600c"
secondaryBackgroundColor = "#1a1a1a"

[theme.light]
primaryColor = "#f0600c"
backgroundColor = "#fcfce4"
secondaryBackgroundColor = "#f0cc90"
textColor = "#070606"

[theme.dark]
primaryColor = "#f0600c"
backgroundColor = "#fcfce4"
secondaryBackgroundColor = "#f0cc90"
textColor = "#070606"

[theme.light.sidebar]
backgroundColor = "#070606"
textColor = "#fcfce4"
primaryColor = "#f0600c"
secondaryBackgroundColor = "#1a1a1a"

[theme.dark.sidebar]
backgroundColor = "#070606"
textColor = "#fcfce4"
primaryColor = "#f0600c"
secondaryBackgroundColor = "#1a1a1a"
